client-id: licensing-service
resource-url: http://host.docker.internal:8083/realms/security-licensing-service/protocol/openid-connect/token
grant-type: password

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://license-database:5432/license-service
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: licensing-service
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8083/realms/security-licensing-service
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8083/realms/security-licensing-service
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: admin
    password: admin
    connection-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
    hostname: licensing-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://license-eurekaserver:8070/eureka/